import pandas as pd
import numpy as np
from src.api_client import trends_data


def generate_mock_ads(trends_df):
    """
    Simulates advertising performance data based on real-world Google Trends interest scores.

    This function models the correlation between market demand (Trends) and corporate
    advertising response, incorporating realistic factors such as operational delay,
    statistical noise, and trend-dependent click-through rates.
    """

    # Initialize dataframe using the datetime index from the Trends source
    mock_df = pd.DataFrame(index=trends_df.index)

    # Extract the primary trend score (Search interest index)
    trend_score = trends_df.iloc[:, 0]

    # --- 1. Ad Spend Generation with Gaussian Noise ---
    # We model spend as a function of market interest + random market volatility
    noise = np.random.normal(0, 20, len(trend_score))
    mock_df['spend_huf'] = (trend_score * 100) + (noise * 50)

    # --- 2. Time-Lag Simulation (Operational Delay) ---
    # Simulates a 2-day delay between market trend detection and budget adjustment
    mock_df['spend_huf'] = mock_df['spend_huf'].shift(2)

    # --- 3. Data Imputation & Cleaning ---
    # Handle missing values generated by the shift operation using mean imputation
    # This ensures consistency for the subsequent integer casting
    mock_df['spend_huf'] = mock_df['spend_huf'].fillna(mock_df['spend_huf'].mean())

    # Finalize spend as an integer value for financial reporting realism
    mock_df['spend_huf'] = mock_df['spend_huf'].astype(int)

    # --- 4. Performance Metrics (Clicks) ---
    # Clicks are modeled based on:
    # - Budget (Spend)
    # - Relevance (Trend Score multiplier)
    # - Performance Variance (Random uniform noise between 0.8x and 1.2x)
    mock_df['clicks'] = (mock_df['spend_huf'] / 50) * (1 + trend_score / 100) * np.random.uniform(0.8, 1.2)
    mock_df['clicks'] = mock_df['clicks'].astype(int)

    # --- 5. Metadata Tagging ---
    mock_df['platform'] = 'Meta Ads'

    return mock_df


if __name__ == "__main__":
    # Internal module testing
    if trends_data is not None:
        ads_data = generate_mock_ads(trends_data)
        print("Successfully generated mock ad data:")
        print(ads_data.head())